### ISSUE TITLE
improve H1 bots

### ISSUE THREAD

**Issue by imbots7274** [BoxOfMysteriez/Box-Bot-Scripts#1]
I want bots to use more Camo and supplydrops Weapon，Make bots look more like real players

**Comment by BoxOfMysteriez** [comment]
They use more camos the higher the difficulty they are set to. I currently don't have MWR installed due to it not running well on my new hardware, although allowing them to use supply drop weapons isn't something that can be easily implemented anyway.

**Comment by imbots7274** [comment]
In fact, at the highest difficulty, bots only use a few classic camos, not the following ones
